[modules]
autoload = yes

; Modules requis par le projet (chargés explicitement même si autoload change)
preload = res_odbc.so
require = res_pjsip.so
require = res_ari.so
require = res_ari_channels.so
require = res_ari_bridges.so
require = res_ari_events.so
require = res_stasis.so
require = app_stasis.so
require = res_stasis_snoop.so
require = app_chanspy.so
require = app_queue.so
require = cdr_manager.so
require = res_prometheus.so
require = res_http_websocket.so

; External Media (Module 3)
require = res_rtp_asterisk.so
