;======================= Transport =======================
[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

;==================== Modèles d'endpoint ==================
[endpoint-internal](!)
type = endpoint
context = internal
disallow = all
allow = ulaw
allow = alaw
allow = slin16
direct_media = no
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes

[auth-userpass](!)
type = auth
auth_type = userpass

[aor-single](!)
type = aor
max_contacts = 1
remove_existing = yes

;===================== Postes agents ======================
[1001](endpoint-internal)
auth = 1001
aors = 1001
callerid = Agent 1001 <1001>

[1001](auth-userpass)
username = 1001
password = agent1001pass

[1001](aor-single)

[1002](endpoint-internal)
auth = 1002
aors = 1002
callerid = Agent 1002 <1002>

[1002](auth-userpass)
username = 1002
password = agent1002pass

[1002](aor-single)

;================== Poste superviseur =====================
[1099](endpoint-internal)
auth = 1099
aors = 1099
callerid = Superviseur <1099>

[1099](auth-userpass)
username = 1099
password = superviseur1099pass

[1099](aor-single)
